name: uva_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  uva_design_system:
    path: ../uva_design_system
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.0
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  geolocator: ^14.0.2
  go_router: ^17.3.0
  google_fonts: ^8.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  http: ^1.6.0
  http_parser: ^4.1.2
  image_picker: ^1.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  mobile_scanner: ^7.2.0
  path: ^1.9.1
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  riverpod_annotation: ^4.0.2
  share_plus: ^13.1.0
  shared_preferences: ^2.5.5
  syncfusion_flutter_pdfviewer: ^33.2.13+1
  url_launcher: ^6.3.2
  widgetbook: ^3.24.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.0
  husky: ^0.1.7
  flutter_launcher_icons: ^0.14.4
  widgetbook_generator: ^3.24.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/pdfs/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21
