#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Obtener el nombre de la rama actual
BRANCH=$(git branch --show-current)

# Solo ejecutar la compilación pesada si estamos empujando a 'main'
if [ "$BRANCH" = "main" ]; then
  echo "🚀 Ejecutando compilación de seguridad antes del push a main..."
  flutter build apk --debug
else
  echo "⏩ Push a la rama '$BRANCH'. Omitiendo compilación local..."
fi
